### ISSUE TITLE
Pin functions

### ISSUE THREAD

**Issue by MotoMongrel** [razorbac91/RazorPad#1]
![CaseConnections](https://github.com/razorbac91/RazorPad/assets/163205263/8cd90657-5d41-4b14-8ba6-8274f0d7728e)
Hi Mate,

Would you be able to update your wiring diagram to show the pin function of the 5 way joystick and also what each of the buttons are for ins 4,5 and 6.  

Thanks Mate.

**Comment by razorbac91** [comment]
Schematics updated and added datasheet reference and image for pins.
