### ISSUE TITLE
Wiring diagram

### ISSUE THREAD

**Issue by MotoMongrel** [razorbac91/RazorPad#2]
![319353262-fb6b67c5-3a9c-4f42-b4b6-5ea17b96bde5](https://github.com/razorbac91/RazorPad/assets/163205263/d10b5f74-53f3-4921-900b-032800291841)

Hi Mate,

Just wanting to check a couple of things before completing the wiring. At the bottom of the pic you have "UP as 1" but instead of going to 1 it goes to pin 5. On the left of the pic, the three push buttons 6,5,4 on one side of each button and on the other side of the buttons you've got 1,2,3, for example 3 is going to pin 4 on the board, what are these number refur to?

The very bottom of the pic (not included) you've got a layout for a 5 way buttom, but what is the A,B,C,D  meant for?

Thanks in advance,

Mongrel

**Comment by razorbac91** [comment]
For the push button: the numbers you see on the top left are just the default of the switch template, i just didn't delete them (will update)

For the five way switch: i need to update te schematic cause thinking about it, i rotated the switch 90° clockwise so isn't correct anymore.

Anyway as generic reference, you can set any GPIO as any direction or push button wiring them to ground to fit your preferences and your specific design arrangement,  just update the code as needed

**Comment by razorbac91** [comment]
Pic updated

**Comment by MotoMongrel** [comment]
Thank you

**Comment by MotoMongrel** [comment]
Hi Mate,

Is there any chance of incorporating an RGB LED into the code and wiring layout, ie, for indication of Bluetooth connected and what mode the controller in is. Thanks in advance, Mongrel.
