### ISSUE TITLE
RGB Led

### ISSUE THREAD

**Issue by MotoMongrel** [razorbac91/RazorPad#3]
Hi Mate,

Is there any chance of incorperating an RGB LED into the code and wiring layout, ie, for indication of bluetooth connected and what mode the concroller in is. Thanks in advance, Mongrel.

**Comment by razorbac91** [comment]
Hi is surely possible to put a led to indicate the BT connection state, but sincerely i would just look at the mobile screen to se if there is the "external keyboard" icon on the notification bar. I can't understand what do you mean for "what mode the controller in is" this code doesn't have "modes" i want to keep it dramatically simple, i voluntarily avoid to put modes on that. Personally if i have music i would control it through the headset/interphone and i use it only with DMD2 (default programming) and Osmand (you can set the input key directly on Osmand configuration)

**Comment by MotoMongrel** [comment]
Hi Mate,A LED Bluetooth connection would be great. I haven’t programmed the board yet so I wasn’t sure weather going from DMD2 to say Osmand you’d need to switch modes to operate either. ThanksMongrelSent from my iPhoneOn 2 Jul 2024, at 7:05 PM, razorbac91 ***@***.***> wrote:﻿
Hi is surely possible to put a led to indicate the BT connection state, but sincerely i would just look at the mobile screen to se if there is the "external keyboard" icon on the notification bar. I can't understand what do you mean for "what mode the controller in is" this code doesn't have "modes" i want to keep it dramatically simple, i voluntarily avoid to put modes on that. Personally if i have music i would control it through the headset/interphone and i use it only with DMD2 (default programming) and Osmand (you can set the input key directly on Osmand configuration)
